---
language: python
services: docker

env:
  global:
    - ROLE_NAME: user-homedir

install:
  # Install test dependencies
  - pip install molecule docker

before_script:
  # Use the actual Ansible Galaxy role name for the project directory
  - cd ../
  - mv ansible-role-$ROLE_NAME phreddrick.$ROLE_NAME
  - cd phreddrick.$ROLE_NAME

script:
  # Run tests
  # - molecule lint
  # - molecule cleanup
  # - molecule destroy
  # - molecule dependency
  # - molecule syntax
  # - molecule create || /bin/true
  # - molecule prepare
  # - molecule converge
  # - molecule idempotence
  # - molecule side-effect
  # - molecule verify
  # - molecule cleanup
  # - molecule destroy
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications
