---
language: python
services: docker

env:
  global:
    - ROLE_NAME: user-homedir
  matrix:
    - MOLECULE_DISTROY: centos8
    - MOLECULE_DISTROY: centos7
    - MOLECULE_DISTROY: centos6
    - MOLECULE_DISTROY: ubuntu2004
    - MOLECULE_DISTROY: ubuntu1804
    - MOLECULE_DISTROY: ubuntu1604
    - MOLECULE_DISTROY: debian8
    - MOLECULE_DISTROY: debian9
    - MOLECULE_DISTROY: debian10

install:
  # Install test dependencies
  - pip install molecule docker

before_script:
  # Use the actual Ansible Galaxy role name for the project directory
  - cd ../
  - mv ansible-role-$ROLE_NAME phreddrick.$ROLE_NAME
  - cd phreddrick.$ROLE_NAME

script:
  # Run tests
  - molecule -s travis test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications
