---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: user_homedir_centos7
    image: centos:7
  - name: golang_user_homedir_centos7
    image: centos:7
    groups:
      - golang
  - name: user_homedir_ubuntu1804
    image: ubuntu:18.04
  - name: golang_user_homedir_ubuntu1804
    image: ubuntu:18.04
    groups:
      - golang
  - name: user_homedir_ubuntu1604
    image: ubuntu:16.04
  - name: user_homedir_ubuntu1404
    image: ubuntu:14.04
  - name: user_homedir_debianjessie
    image: debian:jessie
  - name: user_homedir_debianstretch
    image: debian:stretch
  - name: user_homedir_debianbuster
    image: debian:buster
  - name: user_homedir_debianbullseye
    image: debian:bullseye
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
